Update update_data.yml

diff --git a/.github/workflows/update_data.yml b/.github/workflows/update_data.yml
--- a/.github/workflows/update_data.yml
+++ b/.github/workflows/update_data.yml
@@ -1,8 +1,8 @@
-name: Update Data
+name: Update Dune Data
 
 on:
   schedule:
-    - cron: '0 */3 * * *'
+    - cron: '*/3 * * * *'
   push:
     branches:
       - main
@@ -22,19 +22,22 @@ jobs:
     - name: Install dependencies
       run: |
         python -m pip install --upgrade pip
-        pip install requests dune-client
+        pip install dune-client
 
-    - name: Run data fetch script
+    - name: Fetch data from Dune
+      env:
+        DUNE_API_KEY: ${{ secrets.DUNE_API_KEY }}
       run: |
-        python fetch_data.py
+        python fetch_badges.py
 
     - name: Commit and push changes
       env:
-        ACTIONS_TOKEN: ${{ secrets.ACTIONS_TOKEN }}
+        PERSONAL_ACCESS_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
       run: |
         git config --global user.name 'github-actions'
         git config --global user.email 'github-actions@github.com'
-        git add data.json
-        git commit -m 'Update data'
-        git push https://x-access-token:${{ secrets.ACTIONS_TOKEN }}@github.com/mimika-code/scroll.git
-        
+        touch badge_data.json
+        git add badge_data.json
+        git commit -m 'Update badge data' || echo "Nothing to commit"
+        git push https://x-access-token:${{ secrets.PERSONAL_ACCESS_TOKEN }}@github.com/mimika-code/scroll.git || echo "Push failed"
+
